export const FETCH_TV_SHOWS_SUCCESS = "FETCH_TV_SHOWS_SUCCESS";
export const FETCH_TV_SHOWS_FAILED = "FETCH_TV_SHOWS_FAILED";
export const SAVE_TV_SHOW = "SAVE_TV_SHOW";
export const GET_LIBRARY = "GET_LIBRARY";
export const GET_LIBRARY_FAILED = "GET_LIBRARY_FAILED";
export const SEARCH_TV_SHOWS = "SEARCH_TV_SHOWS";
export const FETCH_SINGLE_SHOW = "FETCH_SINGLE_SHOW";
export const FETCH_SINGLE_SHOW_FAILED = "FETCH_SINGLE_SHOW_FAILED";
